### ISSUE TITLE
次にやること

### ISSUE THREAD

**Issue by tomochika1015** [couragenki/tcg-decks-site#11]
## 元気
竹田のデザインをアップデートする

## 竹田
PCデザインとレギュレーション

## ダイスケ
掲示板のAPI

## トモチカ
合計25記事

**Comment by couragenki** [comment]
校正ツール入れると執筆が楽
https://ics.media/entry/18859/

**Comment by couragenki** [comment]
notionに引っ越し
https://www.notion.so/8-29-5bda260acc2c4894b435be5053e1499d
